services:
  db:
    image: postgres:15  # Use a specific PostgreSQL version (15 is a good stable choice)
    container_name: dnd-dm-db
    restart: unless-stopped  # Restart the container if it fails
    environment:
      POSTGRES_USER: postgres  # Using simpler username
      POSTGRES_PASSWORD: postgres  # Using simpler password
      POSTGRES_DB: dnd_dm      # Database name
    ports:
      - "5432:5432"  # Expose the default PostgreSQL port (5432)
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data to a named volume
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4  # Official pgAdmin 4 image
    container_name: dnd-dm-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}  # Change this!
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-dungeonmaster}      # Change this!
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"  # Expose pgAdmin on port 8080 of the host
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin data
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80/misc/ping"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  db_data:
  pgadmin_data:
